services:
  - type: web
    name: cancelitnowbot
    env: python
    runtime: python-3.10.13  # 🔧 Set exact Python version
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
